// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(lipalightninglibFFI)
import lipalightninglibFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_lipalightninglib_977e_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_lipalightninglib_977e_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a libray of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// A helper class to read values out of a byte buffer.
fileprivate class Reader {
    let data: Data
    var offset: Data.Index

    init(data: Data) {
        self.data = data
        self.offset = 0
    }

    // Reads an integer at the current offset, in big-endian order, and advances
    // the offset on success. Throws if reading the integer would move the
    // offset past the end of the buffer.
    func readInt<T: FixedWidthInteger>() throws -> T {
        let range = offset..<offset + MemoryLayout<T>.size
        guard data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        if T.self == UInt8.self {
            let value = data[offset]
            offset += 1
            return value as! T
        }
        var value: T = 0
        let _ = withUnsafeMutableBytes(of: &value, { data.copyBytes(to: $0, from: range)})
        offset = range.upperBound
        return value.bigEndian
    }

    // Reads an arbitrary number of bytes, to be used to read
    // raw bytes, this is useful when lifting strings
    func readBytes(count: Int) throws -> Array<UInt8> {
        let range = offset..<(offset+count)
        guard data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        var value = [UInt8](repeating: 0, count: count)
        value.withUnsafeMutableBufferPointer({ buffer in
            data.copyBytes(to: buffer, from: range)
        })
        offset = range.upperBound
        return value
    }

    // Reads a float at the current offset.
    @inlinable
    func readFloat() throws -> Float {
        return Float(bitPattern: try readInt())
    }

    // Reads a float at the current offset.
    @inlinable
    func readDouble() throws -> Double {
        return Double(bitPattern: try readInt())
    }

    // Indicates if the offset has reached the end of the buffer.
    @inlinable
    func hasRemaining() -> Bool {
        return offset < data.count
    }
}

// A helper class to write values into a byte buffer.
fileprivate class Writer {
    var bytes: [UInt8]
    var offset: Array<UInt8>.Index

    init() {
        self.bytes = []
        self.offset = 0
    }

    func writeBytes<S>(_ byteArr: S) where S: Sequence, S.Element == UInt8 {
        bytes.append(contentsOf: byteArr)
    }

    // Writes an integer in big-endian order.
    //
    // Warning: make sure what you are trying to write
    // is in the correct type!
    func writeInt<T: FixedWidthInteger>(_ value: T) {
        var value = value.bigEndian
        withUnsafeBytes(of: &value) { bytes.append(contentsOf: $0) }
    }

    @inlinable
    func writeFloat(_ value: Float) {
        writeInt(value.bitPattern)
    }

    @inlinable
    func writeDouble(_ value: Double) {
        writeInt(value.bitPattern)
    }
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: Reader) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: Writer)
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    static func lift(_ buf: RustBuffer) throws -> SwiftType {
        let reader = Reader(data: Data(rustBuffer: buf))
        let value = try read(from: reader)
        if reader.hasRemaining() {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    static func lower(_ value: SwiftType) -> RustBuffer {
          let writer = Writer()
          write(value, into: writer)
          return RustBuffer(bytes: writer.bytes)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: {
        $0.deallocate()
        return UniffiInternalError.unexpectedRustCallError
    })
}

private func rustCallWithError<T, F: FfiConverter>
    (_ errorFfiConverter: F.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T
    where F.SwiftType: Error, F.FfiType == RustBuffer
    {
    try makeRustCall(callback, errorHandler: { return try errorFfiConverter.lift($0) })
}

private func makeRustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T, errorHandler: (RustBuffer) throws -> Error) throws -> T {
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    switch callStatus.code {
        case CALL_SUCCESS:
            return returnedVal

        case CALL_ERROR:
            throw try errorHandler(callStatus.errorBuf)

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    static func read(from buf: Reader) throws -> UInt8 {
        return try lift(buf.readInt())
    }

    static func write(_ value: UInt8, into buf: Writer) {
        buf.writeInt(lower(value))
    }
}

fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    static func read(from buf: Reader) throws -> UInt16 {
        return try lift(buf.readInt())
    }

    static func write(_ value: SwiftType, into buf: Writer) {
        buf.writeInt(lower(value))
    }
}

fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: Reader) throws -> UInt64 {
        return try lift(buf.readInt())
    }

    static func write(_ value: SwiftType, into buf: Writer) {
        buf.writeInt(lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: Reader) throws -> Bool {
        return try lift(buf.readInt())
    }

    static func write(_ value: Bool, into buf: Writer) {
        buf.writeInt(lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: Reader) throws -> String {
        let len: Int32 = try buf.readInt()
        return String(bytes: try buf.readBytes(count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: Writer) {
        let len = Int32(value.utf8.count)
        buf.writeInt(len)
        buf.writeBytes(value.utf8)
    }
}


public protocol LightningNodeProtocol {
    func `getNodeInfo`()  -> NodeInfo
    func `queryLspFee`() throws -> LspFee
    func `connectedToNode`(`node`: NodeAddress)  -> Bool
    func `createInvoice`(`amountMsat`: UInt64, `description`: String) throws -> String
    func `syncGraph`() throws
    
}

public class LightningNode: LightningNodeProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(`config`: Config, `redundantStorageCallback`: RedundantStorageCallback, `lspCallback`: LspCallback) throws {
        self.init(unsafeFromRawPointer: try
    
    rustCallWithError(FfiConverterTypeInitializationError.self) {
    
    lipalightninglib_977e_LightningNode_new(
        FfiConverterTypeConfig.lower(`config`), 
        FfiConverterCallbackInterfaceRedundantStorageCallback.lower(`redundantStorageCallback`), 
        FfiConverterCallbackInterfaceLspCallback.lower(`lspCallback`), $0)
})
    }

    deinit {
        try! rustCall { ffi_lipalightninglib_977e_LightningNode_object_free(pointer, $0) }
    }

    

    
    public func `getNodeInfo`()  -> NodeInfo {
        return try! FfiConverterTypeNodeInfo.lift(
            try!
    rustCall() {
    
    lipalightninglib_977e_LightningNode_get_node_info(self.pointer, $0
    )
}
        )
    }
    public func `queryLspFee`() throws -> LspFee {
        return try FfiConverterTypeLspFee.lift(
            try
    rustCallWithError(FfiConverterTypeLipaError.self) {
    lipalightninglib_977e_LightningNode_query_lsp_fee(self.pointer, $0
    )
}
        )
    }
    public func `connectedToNode`(`node`: NodeAddress)  -> Bool {
        return try! FfiConverterBool.lift(
            try!
    rustCall() {
    
    lipalightninglib_977e_LightningNode_connected_to_node(self.pointer, 
        FfiConverterTypeNodeAddress.lower(`node`), $0
    )
}
        )
    }
    public func `createInvoice`(`amountMsat`: UInt64, `description`: String) throws -> String {
        return try FfiConverterString.lift(
            try
    rustCallWithError(FfiConverterTypeLipaError.self) {
    lipalightninglib_977e_LightningNode_create_invoice(self.pointer, 
        FfiConverterUInt64.lower(`amountMsat`), 
        FfiConverterString.lower(`description`), $0
    )
}
        )
    }
    public func `syncGraph`() throws {
        try
    rustCallWithError(FfiConverterTypeLipaError.self) {
    lipalightninglib_977e_LightningNode_sync_graph(self.pointer, $0
    )
}
    }
    
}


fileprivate struct FfiConverterTypeLightningNode: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = LightningNode

    static func read(from buf: Reader) throws -> LightningNode {
        let v: UInt64 = try buf.readInt()
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    static func write(_ value: LightningNode, into buf: Writer) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        buf.writeInt(UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    static func lift(_ pointer: UnsafeMutableRawPointer) throws -> LightningNode {
        return LightningNode(unsafeFromRawPointer: pointer)
    }

    static func lower(_ value: LightningNode) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public struct ChannelsInfo {
    public var `numChannels`: UInt16
    public var `numUsableChannels`: UInt16
    public var `localBalanceMsat`: UInt64
    public var `inboundCapacityMsat`: UInt64
    public var `outboundCapacityMsat`: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`numChannels`: UInt16, `numUsableChannels`: UInt16, `localBalanceMsat`: UInt64, `inboundCapacityMsat`: UInt64, `outboundCapacityMsat`: UInt64) {
        self.`numChannels` = `numChannels`
        self.`numUsableChannels` = `numUsableChannels`
        self.`localBalanceMsat` = `localBalanceMsat`
        self.`inboundCapacityMsat` = `inboundCapacityMsat`
        self.`outboundCapacityMsat` = `outboundCapacityMsat`
    }
}


extension ChannelsInfo: Equatable, Hashable {
    public static func ==(lhs: ChannelsInfo, rhs: ChannelsInfo) -> Bool {
        if lhs.`numChannels` != rhs.`numChannels` {
            return false
        }
        if lhs.`numUsableChannels` != rhs.`numUsableChannels` {
            return false
        }
        if lhs.`localBalanceMsat` != rhs.`localBalanceMsat` {
            return false
        }
        if lhs.`inboundCapacityMsat` != rhs.`inboundCapacityMsat` {
            return false
        }
        if lhs.`outboundCapacityMsat` != rhs.`outboundCapacityMsat` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`numChannels`)
        hasher.combine(`numUsableChannels`)
        hasher.combine(`localBalanceMsat`)
        hasher.combine(`inboundCapacityMsat`)
        hasher.combine(`outboundCapacityMsat`)
    }
}


fileprivate struct FfiConverterTypeChannelsInfo: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> ChannelsInfo {
        return try ChannelsInfo(
            `numChannels`: FfiConverterUInt16.read(from: buf), 
            `numUsableChannels`: FfiConverterUInt16.read(from: buf), 
            `localBalanceMsat`: FfiConverterUInt64.read(from: buf), 
            `inboundCapacityMsat`: FfiConverterUInt64.read(from: buf), 
            `outboundCapacityMsat`: FfiConverterUInt64.read(from: buf)
        )
    }

    fileprivate static func write(_ value: ChannelsInfo, into buf: Writer) {
        FfiConverterUInt16.write(value.`numChannels`, into: buf)
        FfiConverterUInt16.write(value.`numUsableChannels`, into: buf)
        FfiConverterUInt64.write(value.`localBalanceMsat`, into: buf)
        FfiConverterUInt64.write(value.`inboundCapacityMsat`, into: buf)
        FfiConverterUInt64.write(value.`outboundCapacityMsat`, into: buf)
    }
}


public struct Config {
    public var `network`: Network
    public var `seed`: [UInt8]
    public var `esploraApiUrl`: String
    public var `lspNode`: NodeAddress
    public var `rgsUrl`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`network`: Network, `seed`: [UInt8], `esploraApiUrl`: String, `lspNode`: NodeAddress, `rgsUrl`: String) {
        self.`network` = `network`
        self.`seed` = `seed`
        self.`esploraApiUrl` = `esploraApiUrl`
        self.`lspNode` = `lspNode`
        self.`rgsUrl` = `rgsUrl`
    }
}


extension Config: Equatable, Hashable {
    public static func ==(lhs: Config, rhs: Config) -> Bool {
        if lhs.`network` != rhs.`network` {
            return false
        }
        if lhs.`seed` != rhs.`seed` {
            return false
        }
        if lhs.`esploraApiUrl` != rhs.`esploraApiUrl` {
            return false
        }
        if lhs.`lspNode` != rhs.`lspNode` {
            return false
        }
        if lhs.`rgsUrl` != rhs.`rgsUrl` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`network`)
        hasher.combine(`seed`)
        hasher.combine(`esploraApiUrl`)
        hasher.combine(`lspNode`)
        hasher.combine(`rgsUrl`)
    }
}


fileprivate struct FfiConverterTypeConfig: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> Config {
        return try Config(
            `network`: FfiConverterTypeNetwork.read(from: buf), 
            `seed`: FfiConverterSequenceUInt8.read(from: buf), 
            `esploraApiUrl`: FfiConverterString.read(from: buf), 
            `lspNode`: FfiConverterTypeNodeAddress.read(from: buf), 
            `rgsUrl`: FfiConverterString.read(from: buf)
        )
    }

    fileprivate static func write(_ value: Config, into buf: Writer) {
        FfiConverterTypeNetwork.write(value.`network`, into: buf)
        FfiConverterSequenceUInt8.write(value.`seed`, into: buf)
        FfiConverterString.write(value.`esploraApiUrl`, into: buf)
        FfiConverterTypeNodeAddress.write(value.`lspNode`, into: buf)
        FfiConverterString.write(value.`rgsUrl`, into: buf)
    }
}


public struct LspFee {
    public var `minMsat`: UInt64
    public var `ratePpm`: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`minMsat`: UInt64, `ratePpm`: UInt64) {
        self.`minMsat` = `minMsat`
        self.`ratePpm` = `ratePpm`
    }
}


extension LspFee: Equatable, Hashable {
    public static func ==(lhs: LspFee, rhs: LspFee) -> Bool {
        if lhs.`minMsat` != rhs.`minMsat` {
            return false
        }
        if lhs.`ratePpm` != rhs.`ratePpm` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`minMsat`)
        hasher.combine(`ratePpm`)
    }
}


fileprivate struct FfiConverterTypeLspFee: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> LspFee {
        return try LspFee(
            `minMsat`: FfiConverterUInt64.read(from: buf), 
            `ratePpm`: FfiConverterUInt64.read(from: buf)
        )
    }

    fileprivate static func write(_ value: LspFee, into buf: Writer) {
        FfiConverterUInt64.write(value.`minMsat`, into: buf)
        FfiConverterUInt64.write(value.`ratePpm`, into: buf)
    }
}


public struct NodeAddress {
    public var `pubKey`: String
    public var `address`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`pubKey`: String, `address`: String) {
        self.`pubKey` = `pubKey`
        self.`address` = `address`
    }
}


extension NodeAddress: Equatable, Hashable {
    public static func ==(lhs: NodeAddress, rhs: NodeAddress) -> Bool {
        if lhs.`pubKey` != rhs.`pubKey` {
            return false
        }
        if lhs.`address` != rhs.`address` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`pubKey`)
        hasher.combine(`address`)
    }
}


fileprivate struct FfiConverterTypeNodeAddress: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> NodeAddress {
        return try NodeAddress(
            `pubKey`: FfiConverterString.read(from: buf), 
            `address`: FfiConverterString.read(from: buf)
        )
    }

    fileprivate static func write(_ value: NodeAddress, into buf: Writer) {
        FfiConverterString.write(value.`pubKey`, into: buf)
        FfiConverterString.write(value.`address`, into: buf)
    }
}


public struct NodeInfo {
    public var `nodePubkey`: [UInt8]
    public var `numPeers`: UInt16
    public var `channelsInfo`: ChannelsInfo

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`nodePubkey`: [UInt8], `numPeers`: UInt16, `channelsInfo`: ChannelsInfo) {
        self.`nodePubkey` = `nodePubkey`
        self.`numPeers` = `numPeers`
        self.`channelsInfo` = `channelsInfo`
    }
}


extension NodeInfo: Equatable, Hashable {
    public static func ==(lhs: NodeInfo, rhs: NodeInfo) -> Bool {
        if lhs.`nodePubkey` != rhs.`nodePubkey` {
            return false
        }
        if lhs.`numPeers` != rhs.`numPeers` {
            return false
        }
        if lhs.`channelsInfo` != rhs.`channelsInfo` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`nodePubkey`)
        hasher.combine(`numPeers`)
        hasher.combine(`channelsInfo`)
    }
}


fileprivate struct FfiConverterTypeNodeInfo: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> NodeInfo {
        return try NodeInfo(
            `nodePubkey`: FfiConverterSequenceUInt8.read(from: buf), 
            `numPeers`: FfiConverterUInt16.read(from: buf), 
            `channelsInfo`: FfiConverterTypeChannelsInfo.read(from: buf)
        )
    }

    fileprivate static func write(_ value: NodeInfo, into buf: Writer) {
        FfiConverterSequenceUInt8.write(value.`nodePubkey`, into: buf)
        FfiConverterUInt16.write(value.`numPeers`, into: buf)
        FfiConverterTypeChannelsInfo.write(value.`channelsInfo`, into: buf)
    }
}


public struct Secret {
    public var `mnemonic`: [String]
    public var `passphrase`: String
    public var `seed`: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`mnemonic`: [String], `passphrase`: String, `seed`: [UInt8]) {
        self.`mnemonic` = `mnemonic`
        self.`passphrase` = `passphrase`
        self.`seed` = `seed`
    }
}


extension Secret: Equatable, Hashable {
    public static func ==(lhs: Secret, rhs: Secret) -> Bool {
        if lhs.`mnemonic` != rhs.`mnemonic` {
            return false
        }
        if lhs.`passphrase` != rhs.`passphrase` {
            return false
        }
        if lhs.`seed` != rhs.`seed` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`mnemonic`)
        hasher.combine(`passphrase`)
        hasher.combine(`seed`)
    }
}


fileprivate struct FfiConverterTypeSecret: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> Secret {
        return try Secret(
            `mnemonic`: FfiConverterSequenceString.read(from: buf), 
            `passphrase`: FfiConverterString.read(from: buf), 
            `seed`: FfiConverterSequenceUInt8.read(from: buf)
        )
    }

    fileprivate static func write(_ value: Secret, into buf: Writer) {
        FfiConverterSequenceString.write(value.`mnemonic`, into: buf)
        FfiConverterString.write(value.`passphrase`, into: buf)
        FfiConverterSequenceUInt8.write(value.`seed`, into: buf)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum LogLevel {
    
    case `error`
    case `warn`
    case `info`
    case `debug`
    case `trace`
}

fileprivate struct FfiConverterTypeLogLevel: FfiConverterRustBuffer {
    typealias SwiftType = LogLevel

    static func read(from buf: Reader) throws -> LogLevel {
        let variant: Int32 = try buf.readInt()
        switch variant {
        
        case 1: return .`error`
        
        case 2: return .`warn`
        
        case 3: return .`info`
        
        case 4: return .`debug`
        
        case 5: return .`trace`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: LogLevel, into buf: Writer) {
        switch value {
        
        
        case .`error`:
            buf.writeInt(Int32(1))
        
        
        case .`warn`:
            buf.writeInt(Int32(2))
        
        
        case .`info`:
            buf.writeInt(Int32(3))
        
        
        case .`debug`:
            buf.writeInt(Int32(4))
        
        
        case .`trace`:
            buf.writeInt(Int32(5))
        
        }
    }
}


extension LogLevel: Equatable, Hashable {}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum Network {
    
    case `bitcoin`
    case `testnet`
    case `signet`
    case `regtest`
}

fileprivate struct FfiConverterTypeNetwork: FfiConverterRustBuffer {
    typealias SwiftType = Network

    static func read(from buf: Reader) throws -> Network {
        let variant: Int32 = try buf.readInt()
        switch variant {
        
        case 1: return .`bitcoin`
        
        case 2: return .`testnet`
        
        case 3: return .`signet`
        
        case 4: return .`regtest`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: Network, into buf: Writer) {
        switch value {
        
        
        case .`bitcoin`:
            buf.writeInt(Int32(1))
        
        
        case .`testnet`:
            buf.writeInt(Int32(2))
        
        
        case .`signet`:
            buf.writeInt(Int32(3))
        
        
        case .`regtest`:
            buf.writeInt(Int32(4))
        
        }
    }
}


extension Network: Equatable, Hashable {}



public enum InitializationError {

    
    
    // Simple error enums only carry a message
    case AsyncRuntime(message: String)
    
    // Simple error enums only carry a message
    case ChainMonitorWatchChannel(message: String)
    
    // Simple error enums only carry a message
    case ChainSync(message: String)
    
    // Simple error enums only carry a message
    case ChannelMonitorBackup(message: String)
    
    // Simple error enums only carry a message
    case EsploraClient(message: String)
    
    // Simple error enums only carry a message
    case KeysManager(message: String)
    
    // Simple error enums only carry a message
    case Logic(message: String)
    
    // Simple error enums only carry a message
    case PeerConnection(message: String)
    
    // Simple error enums only carry a message
    case PublicKey(message: String)
    
    // Simple error enums only carry a message
    case SecretGeneration(message: String)
    
}

fileprivate struct FfiConverterTypeInitializationError: FfiConverterRustBuffer {
    typealias SwiftType = InitializationError

    static func read(from buf: Reader) throws -> InitializationError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .AsyncRuntime(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .ChainMonitorWatchChannel(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .ChainSync(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 4: return .ChannelMonitorBackup(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 5: return .EsploraClient(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 6: return .KeysManager(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 7: return .Logic(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 8: return .PeerConnection(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 9: return .PublicKey(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 10: return .SecretGeneration(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: InitializationError, into buf: Writer) {
        switch value {

        

        
        case let .AsyncRuntime(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .ChainMonitorWatchChannel(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .ChainSync(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)
        case let .ChannelMonitorBackup(message):
            buf.writeInt(Int32(4))
            FfiConverterString.write(message, into: buf)
        case let .EsploraClient(message):
            buf.writeInt(Int32(5))
            FfiConverterString.write(message, into: buf)
        case let .KeysManager(message):
            buf.writeInt(Int32(6))
            FfiConverterString.write(message, into: buf)
        case let .Logic(message):
            buf.writeInt(Int32(7))
            FfiConverterString.write(message, into: buf)
        case let .PeerConnection(message):
            buf.writeInt(Int32(8))
            FfiConverterString.write(message, into: buf)
        case let .PublicKey(message):
            buf.writeInt(Int32(9))
            FfiConverterString.write(message, into: buf)
        case let .SecretGeneration(message):
            buf.writeInt(Int32(10))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension InitializationError: Equatable, Hashable {}

extension InitializationError: Error { }


public enum LipaError {

    
    
    // Simple error enums only carry a message
    case InvalidInput(message: String)
    
    // Simple error enums only carry a message
    case RuntimeError(message: String)
    
    // Simple error enums only carry a message
    case PermanentFailure(message: String)
    
}

fileprivate struct FfiConverterTypeLipaError: FfiConverterRustBuffer {
    typealias SwiftType = LipaError

    static func read(from buf: Reader) throws -> LipaError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .InvalidInput(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .RuntimeError(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .PermanentFailure(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: LipaError, into buf: Writer) {
        switch value {

        

        
        case let .InvalidInput(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .RuntimeError(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .PermanentFailure(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension LipaError: Equatable, Hashable {}

extension LipaError: Error { }


public enum LspError {

    
    
    // Simple error enums only carry a message
    case Grpc(message: String)
    
    // Simple error enums only carry a message
    case Network(message: String)
    
    // Simple error enums only carry a message
    case UnexpectedUniFfi(message: String)
    
}

fileprivate struct FfiConverterTypeLspError: FfiConverterRustBuffer {
    typealias SwiftType = LspError

    static func read(from buf: Reader) throws -> LspError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .Grpc(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .Network(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .UnexpectedUniFfi(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: LspError, into buf: Writer) {
        switch value {

        

        
        case let .Grpc(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .Network(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .UnexpectedUniFfi(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension LspError: Equatable, Hashable {}

extension LspError: Error { }


public enum RuntimeError {

    
    
    // Simple error enums only carry a message
    case ChainSync(message: String)
    
    // Simple error enums only carry a message
    case InvalidAddress(message: String)
    
    // Simple error enums only carry a message
    case InvalidPubKey(message: String)
    
    // Simple error enums only carry a message
    case Logic(message: String)
    
    // Simple error enums only carry a message
    case PeerConnection(message: String)
    
}

fileprivate struct FfiConverterTypeRuntimeError: FfiConverterRustBuffer {
    typealias SwiftType = RuntimeError

    static func read(from buf: Reader) throws -> RuntimeError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .ChainSync(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .InvalidAddress(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .InvalidPubKey(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 4: return .Logic(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 5: return .PeerConnection(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: RuntimeError, into buf: Writer) {
        switch value {

        

        
        case let .ChainSync(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .InvalidAddress(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .InvalidPubKey(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)
        case let .Logic(message):
            buf.writeInt(Int32(4))
            FfiConverterString.write(message, into: buf)
        case let .PeerConnection(message):
            buf.writeInt(Int32(5))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension RuntimeError: Equatable, Hashable {}

extension RuntimeError: Error { }

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate typealias Handle = UInt64
fileprivate class ConcurrentHandleMap<T> {
    private var leftMap: [Handle: T] = [:]
    private var counter: [Handle: UInt64] = [:]
    private var rightMap: [ObjectIdentifier: Handle] = [:]

    private let lock = NSLock()
    private var currentHandle: Handle = 0
    private let stride: Handle = 1

    func insert(obj: T) -> Handle {
        lock.withLock {
            let id = ObjectIdentifier(obj as AnyObject)
            let handle = rightMap[id] ?? {
                currentHandle += stride
                let handle = currentHandle
                leftMap[handle] = obj
                rightMap[id] = handle
                return handle
            }()
            counter[handle] = (counter[handle] ?? 0) + 1
            return handle
        }
    }

    func get(handle: Handle) -> T? {
        lock.withLock {
            leftMap[handle]
        }
    }

    func delete(handle: Handle) {
        remove(handle: handle)
    }

    @discardableResult
    func remove(handle: Handle) -> T? {
        lock.withLock {
            defer { counter[handle] = (counter[handle] ?? 1) - 1 }
            guard counter[handle] == 1 else { return leftMap[handle] }
            let obj = leftMap.removeValue(forKey: handle)
            if let obj = obj {
                rightMap.removeValue(forKey: ObjectIdentifier(obj as AnyObject))
            }
            return obj
        }
    }
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0

// Declaration and FfiConverters for LspCallback Callback Interface

public protocol LspCallback : AnyObject {
    func `channelInformation`() throws -> [UInt8]
    func `registerPayment`(`bytes`: [UInt8]) throws
    
}

// The ForeignCallback that is passed to Rust.
fileprivate let foreignCallbackCallbackInterfaceLspCallback : ForeignCallback =
    { (handle: Handle, method: Int32, args: RustBuffer, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
        func `invokeChannelInformation`(_ swiftCallbackInterface: LspCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }
            let result = try swiftCallbackInterface.`channelInformation`()
            let writer = Writer()
                FfiConverterSequenceUInt8.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        func `invokeRegisterPayment`(_ swiftCallbackInterface: LspCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            try swiftCallbackInterface.`registerPayment`(
                    `bytes`:  try FfiConverterSequenceUInt8.read(from: reader)
                    )
            return RustBuffer()
                // TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        

        let cb: LspCallback
        do {
            cb = try FfiConverterCallbackInterfaceLspCallback.lift(handle)
        } catch {
            out_buf.pointee = FfiConverterString.lower("LspCallback: Invalid handle")
            return -1
        }

        switch method {
            case IDX_CALLBACK_FREE:
                FfiConverterCallbackInterfaceLspCallback.drop(handle: handle)
                // No return value.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return 0
            case 1:
                do {
                    out_buf.pointee = try `invokeChannelInformation`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error as LspError {
                    out_buf.pointee = FfiConverterTypeLspError.lower(error)
                    return -2
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            case 2:
                do {
                    out_buf.pointee = try `invokeRegisterPayment`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error as LspError {
                    out_buf.pointee = FfiConverterTypeLspError.lower(error)
                    return -2
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            
            // This should never happen, because an out of bounds method index won't
            // ever be used. Once we can catch errors, we should return an InternalError.
            // https://github.com/mozilla/uniffi-rs/issues/351
            default:
                // An unexpected error happened.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return -1
        }
    }

// FFIConverter protocol for callback interfaces
fileprivate struct FfiConverterCallbackInterfaceLspCallback {
    // Initialize our callback method with the scaffolding code
    private static var callbackInitialized = false
    private static func initCallback() {
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
                ffi_lipalightninglib_977e_LspCallback_init_callback(foreignCallbackCallbackInterfaceLspCallback, err)
        }
    }
    private static func ensureCallbackinitialized() {
        if !callbackInitialized {
            initCallback()
            callbackInitialized = true
        }
    }

    static func drop(handle: Handle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = ConcurrentHandleMap<LspCallback>()
}

extension FfiConverterCallbackInterfaceLspCallback : FfiConverter {
    typealias SwiftType = LspCallback
    // We can use Handle as the FFIType because it's a typealias to UInt64
    typealias FfiType = Handle

    static func lift(_ handle: Handle) throws -> SwiftType {
        ensureCallbackinitialized();
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    static func read(from buf: Reader) throws -> SwiftType {
        ensureCallbackinitialized();
        let handle: Handle = try buf.readInt()
        return try lift(handle)
    }

    static func lower(_ v: SwiftType) -> Handle {
        ensureCallbackinitialized();
        return handleMap.insert(obj: v)
    }

    static func write(_ v: SwiftType, into buf: Writer) {
        ensureCallbackinitialized();
        buf.writeInt(lower(v))
    }
}



// Declaration and FfiConverters for RedundantStorageCallback Callback Interface

public protocol RedundantStorageCallback : AnyObject {
    func `objectExists`(`bucket`: String, `key`: String)  -> Bool
    func `getObject`(`bucket`: String, `key`: String)  -> [UInt8]
    func `checkHealth`(`bucket`: String)  -> Bool
    func `putObject`(`bucket`: String, `key`: String, `value`: [UInt8])  -> Bool
    func `listObjects`(`bucket`: String)  -> [String]
    func `deleteObject`(`bucket`: String, `key`: String)  -> Bool
    
}

// The ForeignCallback that is passed to Rust.
fileprivate let foreignCallbackCallbackInterfaceRedundantStorageCallback : ForeignCallback =
    { (handle: Handle, method: Int32, args: RustBuffer, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
        func `invokeObjectExists`(_ swiftCallbackInterface: RedundantStorageCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            let result = swiftCallbackInterface.`objectExists`(
                    `bucket`:  try FfiConverterString.read(from: reader), 
                    `key`:  try FfiConverterString.read(from: reader)
                    )
            let writer = Writer()
                FfiConverterBool.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        func `invokeGetObject`(_ swiftCallbackInterface: RedundantStorageCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            let result = swiftCallbackInterface.`getObject`(
                    `bucket`:  try FfiConverterString.read(from: reader), 
                    `key`:  try FfiConverterString.read(from: reader)
                    )
            let writer = Writer()
                FfiConverterSequenceUInt8.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        func `invokeCheckHealth`(_ swiftCallbackInterface: RedundantStorageCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            let result = swiftCallbackInterface.`checkHealth`(
                    `bucket`:  try FfiConverterString.read(from: reader)
                    )
            let writer = Writer()
                FfiConverterBool.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        func `invokePutObject`(_ swiftCallbackInterface: RedundantStorageCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            let result = swiftCallbackInterface.`putObject`(
                    `bucket`:  try FfiConverterString.read(from: reader), 
                    `key`:  try FfiConverterString.read(from: reader), 
                    `value`:  try FfiConverterSequenceUInt8.read(from: reader)
                    )
            let writer = Writer()
                FfiConverterBool.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        func `invokeListObjects`(_ swiftCallbackInterface: RedundantStorageCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            let result = swiftCallbackInterface.`listObjects`(
                    `bucket`:  try FfiConverterString.read(from: reader)
                    )
            let writer = Writer()
                FfiConverterSequenceString.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        func `invokeDeleteObject`(_ swiftCallbackInterface: RedundantStorageCallback, _ args: RustBuffer) throws -> RustBuffer {
        defer { args.deallocate() }

            let reader = Reader(data: Data(rustBuffer: args))
            let result = swiftCallbackInterface.`deleteObject`(
                    `bucket`:  try FfiConverterString.read(from: reader), 
                    `key`:  try FfiConverterString.read(from: reader)
                    )
            let writer = Writer()
                FfiConverterBool.write(result, into: writer)
                return RustBuffer(bytes: writer.bytes)// TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351

        }
        

        let cb: RedundantStorageCallback
        do {
            cb = try FfiConverterCallbackInterfaceRedundantStorageCallback.lift(handle)
        } catch {
            out_buf.pointee = FfiConverterString.lower("RedundantStorageCallback: Invalid handle")
            return -1
        }

        switch method {
            case IDX_CALLBACK_FREE:
                FfiConverterCallbackInterfaceRedundantStorageCallback.drop(handle: handle)
                // No return value.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return 0
            case 1:
                do {
                    out_buf.pointee = try `invokeObjectExists`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            case 2:
                do {
                    out_buf.pointee = try `invokeGetObject`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            case 3:
                do {
                    out_buf.pointee = try `invokeCheckHealth`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            case 4:
                do {
                    out_buf.pointee = try `invokePutObject`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            case 5:
                do {
                    out_buf.pointee = try `invokeListObjects`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            case 6:
                do {
                    out_buf.pointee = try `invokeDeleteObject`(cb, args)
                    // Value written to out buffer.
                    // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                    return 1
                } catch let error {
                    out_buf.pointee = FfiConverterString.lower(String(describing: error))
                    return -1
                }
            
            // This should never happen, because an out of bounds method index won't
            // ever be used. Once we can catch errors, we should return an InternalError.
            // https://github.com/mozilla/uniffi-rs/issues/351
            default:
                // An unexpected error happened.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return -1
        }
    }

// FFIConverter protocol for callback interfaces
fileprivate struct FfiConverterCallbackInterfaceRedundantStorageCallback {
    // Initialize our callback method with the scaffolding code
    private static var callbackInitialized = false
    private static func initCallback() {
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
                ffi_lipalightninglib_977e_RedundantStorageCallback_init_callback(foreignCallbackCallbackInterfaceRedundantStorageCallback, err)
        }
    }
    private static func ensureCallbackinitialized() {
        if !callbackInitialized {
            initCallback()
            callbackInitialized = true
        }
    }

    static func drop(handle: Handle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = ConcurrentHandleMap<RedundantStorageCallback>()
}

extension FfiConverterCallbackInterfaceRedundantStorageCallback : FfiConverter {
    typealias SwiftType = RedundantStorageCallback
    // We can use Handle as the FFIType because it's a typealias to UInt64
    typealias FfiType = Handle

    static func lift(_ handle: Handle) throws -> SwiftType {
        ensureCallbackinitialized();
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    static func read(from buf: Reader) throws -> SwiftType {
        ensureCallbackinitialized();
        let handle: Handle = try buf.readInt()
        return try lift(handle)
    }

    static func lower(_ v: SwiftType) -> Handle {
        ensureCallbackinitialized();
        return handleMap.insert(obj: v)
    }

    static func write(_ v: SwiftType, into buf: Writer) {
        ensureCallbackinitialized();
        buf.writeInt(lower(v))
    }
}

fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    static func write(_ value: [UInt8], into buf: Writer) {
        let len = Int32(value.count)
        buf.writeInt(len)
        for item in value {
            FfiConverterUInt8.write(item, into: buf)
        }
    }

    static func read(from buf: Reader) throws -> [UInt8] {
        let len: Int32 = try buf.readInt()
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: Writer) {
        let len = Int32(value.count)
        buf.writeInt(len)
        for item in value {
            FfiConverterString.write(item, into: buf)
        }
    }

    static func read(from buf: Reader) throws -> [String] {
        let len: Int32 = try buf.readInt()
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: buf))
        }
        return seq
    }
}

public func `initNativeLoggerOnce`(`minLevel`: LogLevel)  {
    try!
    
    rustCall() {
    
    lipalightninglib_977e_init_native_logger_once(
        FfiConverterTypeLogLevel.lower(`minLevel`), $0)
}
}


public func `generateSecret`(`passphrase`: String) throws -> Secret {
    return try FfiConverterTypeSecret.lift(
        try
    
    rustCallWithError(FfiConverterTypeLipaError.self) {
    
    lipalightninglib_977e_generate_secret(
        FfiConverterString.lower(`passphrase`), $0)
}
    )
}



public func `mnemonicToSecret`(`mnemonicString`: [String], `passphrase`: String) throws -> Secret {
    return try FfiConverterTypeSecret.lift(
        try
    
    rustCallWithError(FfiConverterTypeLipaError.self) {
    
    lipalightninglib_977e_mnemonic_to_secret(
        FfiConverterSequenceString.lower(`mnemonicString`), 
        FfiConverterString.lower(`passphrase`), $0)
}
    )
}



/**
 * Top level initializers and tear down methods.
 *
 * This is generated by uniffi.
 */
public enum LipalightninglibLifecycle {
    /**
     * Initialize the FFI and Rust library. This should be only called once per application.
     */
    func initialize() {
    }
}